### ISSUE TITLE
Package of version 1.1.4 is missing the lib folder

### ISSUE THREAD

**Issue by jurgenhaas** [doctrine/deprecations#72] opened 2024-12-09 06:54 UTC
Just found some Drupal sites broken this morning and found out, that the 1.1.4 package is missing the lib folder.

**Comment by greg0ire** [comment] 2024-12-09 07:29
Yes, it was moved to `src`… but that shouldn't matter, since autoloading is properly setup: https://github.com/doctrine/deprecations/blob/31610dbb31faa98e6b5447b62340826f54fbc4e9/composer.json#L22

**Comment by jurgenhaas** [comment] 2024-12-09 08:07
Hmm, I have to check what's going wrong then. Some sites got updated and work well with the src folder, others can't find it and print a message that the lib directory is missing. I'll have to look into the autoloader, I guess.

**Comment by derrabus** [comment] 2024-12-09 08:17
I'm closing for now because the missing folder is not a bug. If you find out anything that needs a fix on our side, please get back to us!

**Closed as not planned by derrabus** 2024-12-09 08:17 UTC

**Comment by jurgenhaas** [comment] 2024-12-09 08:46
Just for the record: On some sites I got and error like `Warning: include(/var/www/drupal/live/vendor/composer/../doctrine/deprecations/lib/Doctrine/Deprecations/Deprecation.php): Failed to open stream: No such file or directory in include() (Zeile 576 in /var/www/drupal/live/vendor/composer/ClassLoader.php) ` where the class loader really wanted to load from the old location. Clearing cache multiple times didn't resolve the issue. But as soon as I provided the old lib directory, the problem was gone.

Even more so, when afterwards removing that old lib directory again, the problem did NOT come back, This looks like some odd caching that didn't refresh until the old code was present for a short period just to reset the autoloader, I guess.

**Comment by jurgenhaas** [comment] 2024-12-09 09:01
Could that be an APCu issue? Looks like restarting PHP-FPM which also resets APCu would also fix this issue.

**Comment by greg0ire** [comment] 2024-12-09 10:21
~Sounds unlikely, but you probably want to ask this to people who know Drupal.~

Apparently this is not tied to Drupal either

**Comment by derrabus** [comment] 2024-12-09 12:36
If you enable Composer's APCu autoloader, then yes, you could clear the APCu cache when installing dependencies.

**Comment by junowilderness** [comment] 2024-12-10 15:15
Would it be possible in future to conduct a class relocation via a deprecation process?

**Comment by greg0ire** [comment] 2024-12-10 16:10
How would you do that?

**Comment by junowilderness** [comment] 2024-12-10 18:56
I think that creating new classes _with new namepaces_ while deprecating the original classes, and configuring Composer's autoloader with both the original and new namespaces, would avoid this minor breaking change.

That is of course more to deal with in terms of tasks like documentation updates, libraries that use this project having to change imports, and probably things I haven't thought about. And in reality, the relocation of the main namespace mapping is unlikely in future. So take this comment as you see fit.

**Comment by greg0ire** [comment] 2024-12-10 19:31
Ok, then I hope you don't mind if we ignore it, because what you are proposing is a major migration. You're proposing to modify literal thousands of projects to avoid a "minor breaking change" which IMO, is not a breaking change at all. We never made a promise to be compatible with old cache entries. I do not know what deploy tool you use, but clearing your cache on deploy is probably what you should aim for here.

You're right that it's unlikely to happen again for this library or for other doctrine libraries the majority was migrated to `src` , and I don't recall seeing complaints.

You should bear in mind though that we reserve the right to modify the directory for each and every release, and configure your deployment tool accordingly. Apparently, there are options for to do this built-in some deploy tools, maybe there is one for yours as well: https://deployer.org/docs/8.x/contrib/cachetool#usage

**Comment by junowilderness** [comment] 2024-12-10 19:35
To be absolutely clear my own apps are unaffected by this as we restart FPM on deploy with Deployer in fact. But I understand you are not speaking only to me.

**Comment by greg0ire** [comment] 2024-12-10 19:40
Not quite on-topic, but I wrote [this](https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf), it might be an interesting read for you since you mentioned deprecating classes.

**Comment by derrabus** [comment] 2024-12-10 20:30
> I think that creating new classes _with new namepaces_ while deprecating the original classes, and configuring Composer's autoloader with both the original and new namespaces, would avoid this minor breaking change.

Sorry, no. Not happening. Why on earth would we want to rename all classes? 😱 

We did not change the namespace at all and neither did we intend to do so. The APCu class loader is a footgun handed to you by Composer. I don't see any reason to implement complicated migration paths if a simple FPM restart fixes the problem.
